services:
  vault_migration_service:
    build:
      context: .
      args:
        HF_TOKEN: ${HF_TOKEN:-}
    ports:
      - "5000:5000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      
      # HTTP Router Configuration
      - "traefik.http.routers.vault-router.rule=Host(`datamigration.getpatronus.com`)"
      - "traefik.http.routers.vault-router.entrypoints=websecure"
      - "traefik.http.routers.vault-router.tls=true"
      - "traefik.http.routers.vault-router.tls.certresolver=myresolver"
      - "traefik.http.services.vault-service.loadbalancer.server.port=5000"

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
