services:
  vault_migration_service:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      SECRET_KEY: "secret-key"  
      POSTGRES_DB: migration_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yMnE1i6Z27RG6JCah
      DATABASE_URL: postgres.chsgq28yetgt.ap-south-1.rds.amazonaws.com
      DB_PORT: 5432
    # labels:
    #   - "traefik.enable=true"
      
    #   # HTTP Router Configuration
    #   - "traefik.http.routers.vault-router.rule=Host(`datamigration.getpatronus.com`)"
    #   - "traefik.http.routers.vault-router.entrypoints=websecure"
    #   - "traefik.http.routers.vault-router.tls=true"
    #   - "traefik.http.routers.vault-router.tls.certresolver=myresolver"
    #   - "traefik.http.services.vault-service.loadbalancer.server.port=5000"

    # networks:
    #   - traefik_network

# networks:
#   traefik_network:
#     external: true
