"""Initial migration

Revision ID: a0446fa2e830
Revises: 
Create Date: 2025-04-17 23:47:58.099335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0446fa2e830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connector_id', sa.String(), nullable=False),
    sa.Column('realm_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('primary_pii_type', sa.String(), nullable=True),
    sa.Column('primary_pii_match_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_scan_id', sa.Integer(), nullable=True),
    sa.Column('pii_type', sa.String(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['column_scan_id'], ['column_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_anomalies')
    op.drop_table('column_scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
